version: '3.7'

services:

  #
  # Public node
  #
  neo-testnet-node-public:
    image: okertanov/neo-testnet-node:latest
    container_name: neo-testnet-node-public
    hostname: neo-testnet-node-public
    ports:
      - 20332:20332
      - 20333:20333
      - 20334:20334
    networks:
      - nxa-public-net
    depends_on:
      - rabbitmq
    volumes:
        - neo-node-data-public:/neo-node-data
        - type: bind
          source: ./config/testnet/public/config.json
          target: /neo-node/config.json
          read_only: true
        - type: bind
          source: ./config/testnet/public/plugins/ApplicationLogs/config.json
          target: /neo-node/Plugins/ApplicationLogs/config.json
          read_only: true
        - type: bind
          source: ./config/testnet/public/plugins/DBFTPlugin/config.json
          target: /neo-node/Plugins/DBFTPlugin/config.json
          read_only: true
        - type: bind
          source: ./config/testnet/public/plugins/OracleService/config.json
          target: /neo-node/Plugins/OracleService/config.json
          read_only: true
        - type: bind
          source: ./config/testnet/public/plugins/TokensTracker/config.json
          target: /neo-node/Plugins/TokensTracker/config.json
          read_only: true
        - type: bind
          source: ./config/testnet/public/plugins/RpcServer/config.json
          target: /neo-node/Plugins/RpcServer/config.json
          read_only: true
        - type: bind
          source: ./config/testnet/public/plugins/StatesDumper/config.json
          target: /neo-node/Plugins/StatesDumper/config.json
          read_only: true
        - type: bind
          source: ./config/testnet/public/plugins/StateService/config.json
          target: /neo-node/Plugins/StateService/config.json
          read_only: true
        - type: bind
          source: ./config/testnet/public/plugins/NXABlockListener/config.json
          target: /neo-node/Plugins/NXABlockListener/config.json
          read_only: true
        - type: bind
          source: ./config/testnet/public/plugins/NXAExtendedRpc/config.json
          target: /neo-node/Plugins/NXAExtendedRpc/config.json
          read_only: true
    command: tail -f /dev/null


  # From: https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
  # WARNING: DEV ONLY
  #
  pgadmin:
    image: dpage/pgadmin4
    container_name: nxa-open-api-pgadmin
    hostname: "nxa-open-api-pgadmin"
    networks:
      - nxa-public-net
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80

  #
  # RabbitMQ
  # From:
  #   https://zgadzaj.com/development/docker/docker-compose/containers/rabbitmq
  #   https://github.com/micahhausler/rabbitmq-compose/blob/master/docker-compose.yml
  #
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    hostname: "rabbitmq"
    networks:
      - nxa-public-net
    labels:
      NAME: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672

  #
  # CaaS
  #
  nxa-sc-caas:
    image: okertanov/nxa-sc-caas:latest
    container_name: nxa-sc-caas
    hostname: "nxa-sc-caas"
    depends_on:
      - nxa-open-api-database
    networks:
      - nxa-public-net
    ports:
      - 5500:5500
    environment:
      # DB
      API_DB_HOST: ${API_DB_HOST}
      API_DB_PORT: ${API_DB_PORT}
      API_DB_DATABASE: ${API_DB_DATABASE}
      API_DB_USER: ${API_DB_USER}
      API_DB_PASSWORD: ${API_DB_PASSWORD}
      # RMQ
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      MQ_EXCHANGE_CAAS: ${MQ_EXCHANGE_CAAS}

  #
  # Portal
  #
  polaris-portal:
    image: okertanov/polaris-portal:latest
    container_name: polaris-portal
    hostname: "polaris-portal"
    depends_on:
      - neo-testnet-node-public
    networks:
      - nxa-public-net
    ports:
      - 4200:80

volumes:
    neo-node-data-public:
    nxa-open-api-database-data:

networks:
  nxa-public-net:
    external: false

secrets:
  apitokens:
    file: config/caas/caas-db-apitokens.txt
